### PR TITLE
Removed the bullets next to the list elements ( the icons)

### PR DESCRIPTION
**Pull request by Moyib**

### CODE REVIEW

**Comment by enolife** [comment]
Hi @Moyib, it seems this has already been fixed in the remote repo and you're not in sync. Try running
 **git fetch origin**

**Comment by enolife** [comment]
Here's the commit:
https://github.com/enolife/login-page/commit/69f650337cb64d1aba74f2085e9902762a1dae9a?diff=split

**Comment by Moyib** [comment]
Okay seen.

**Comment by enolife** [comment]
Thank you

**Pull request closed without merging**
